blank_issues_enabled: false
contact_links:
  - name: 💬 Need help? (Q&A)
    url: https://github.com/MartinNovan/PrintBuddy3D/discussions
    about: Ask the community or search for tutorials if you have issues with the application, but it's not a bug.