name: ⭐ Feature Request
description: Suggest an feature or enhancement for PrintBuddy3D that would make it more useful for you or others.
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this feature?
      description: |
        Please search to see if an issue already exists for a feature, or perhaps one similar.
        You can then comment and react so that we know know much interest there is in the feature request.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: It should do [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context, images or screenshots about the feature request here.
    validations:
      required: false